### ISSUE TITLE
Magic Constants

### ISSUE THREAD

**Issue by cycne** [nanosonde/bcgen#13]
Magic Constants like `__DIR__` and `__FILE__`  keep value of compiling path.
Is there a way to get the runtime value of `__FILE__` ??

Thanks

**Comment by vjardin** [comment]
It is not on my TODO list, I do not change the path. You are right, it would be a nice feature. You are welcomed to contribute about it.

**Comment by ghost** [comment]
> It is not on my TODO list, I do not change the path. You are right, it would be a nice feature. You are welcomed to contribute about it.

Some very common feature is required. What i should to do? add it? NOOO, i will say that is not my business

**Comment by ghost** [comment]
So, why not to use phpAPI/zend macro to change constant value to the constant Array call, or "constant()" function call?
